### ISSUE TITLE
[FEAT] /edit/[[id]] UI

### ISSUE THREAD

**Issue by CookieHCl** [S7dmnd/satisfactory-planner#3]
# 개요

line 생성/수정 페이지

# 우선순위

- Stage 1 - 즉시
- Stage 2 - 즉시 전부 끝나면 바로 하기
- Stage 3 - 병렬로 심심할때마다

# Stage 1

생성 페이지

[[id]]가 없을 경우 생성 페이지

- [x] factory-line페이지에 생성버튼 만들고 리다이렉트
- [x] 생성 페이지 만들기
  - [x] 레시피는 목록으로 선택가능 (일단 임시로)
- [x] 전체 갯수, TODO 갯수 보여주기

# Stage 2

수정 페이지

[[id]]가 있을 경우 수정 페이지

- [x] 수정할 라인 받아오기
- [x] 라인 정보대로 보여주기
- [x] +page.ts에 receiptList, factoryList & row (if [[id]]) fetch해서 props로 +page.svelte로 넘기기 (코드 수정)
# Stage 3

페이지 기능 추가

- [x] 레시피 선택 개선
  - [x] 레시피 목록 검색기능
  - [x] 대체레시피 여부 표시
- [x] 레시피 각 템별 개수 표시
- [ ] 소머슬롭 고려 (DB에서도)
